services:
  db:
    image: postgres:15-alpine
    container_name: novaq-db
    restart: always
    environment:
      POSTGRES_DB: novaqdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: novaq-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: dev
      DATABASE_URL: jdbc:postgresql://db:5432/novaqdb
      DATABASE_USER: postgres
      DATABASE_PASSWORD: rootpassword
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION_HOURS: ${JWT_EXPIRATION_HOURS}
      MP_ACCESS_TOKEN: ${MP_ACCESS_TOKEN}
      URL: ${URL}

volumes:
  postgres_data:
