# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# H2 console disabled in production
spring.h2.console.enabled=false

# JWT Token Configuration
JWT_SECRET=${JWT_SECRET}
api.security.token.expiration_hours=${JWT_EXPIRATION_HOURS}

# Mercado Pago
mp_access_token=${MP_ACCESS_TOKEN}

# NGROK / URL de notificação
url=${URL}

# Admin
admin_password=${ADMIN_PASSWORD}
email_admin=${EMAIL_ADMIN}

# Logging
logging.level.org.springframework.security=INFO
