spring.application.name=novaq

# Configuração do H2
spring.datasource.url=jdbc:h2:mem:novaqdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Dialeto do Hibernate para H2
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cria/Atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update


# Configurações TOKEN JWT
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration_hours=${JWT_EXPIRATION_HOURS:2}


# Mercado Pago
mp_access_token=${MP_ACCESS_TOKEN}

#NGROK
url=${URL}

logging.level.org.springframework.security=TRACE