# PostgreSQL Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD:}
spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate

# H2 console disabled in production
spring.h2.console.enabled=false

# Logging
logging.level.org.springframework.security=INFO
