spring.application.name=novaq

# JWT Token Configuration
api.security.token.secret=${JWT_SECRET}
api.security.token.expiration_hours=${JWT_EXPIRATION_HOURS}

# Mercado Pago
mp_access_token=${MP_ACCESS_TOKEN}

# NGROK / URL de notificação
url=${URL}

# Admin
admin_password=${ADMIN_PASSWORD}
email_admin=${EMAIL_ADMIN}
